#pragma once

const int DIGIMON_DEFENCE_INTRO_PHASE = 0;
const int DIGIMON_DEFENCE_STAGE1_PHASE = 2;
const int DIGIMON_DEFENCE_STAGE2_PHASE = 3;
const int DIGIMON_DEFENCE_STAGE3_PHASE = 4;
const int DIGIMON_DEFENCE_STAGE4_PHASE = 5;
const int DIGIMON_DEFENCE_BOSS_PHASE = 6;
const int DIGIMON_DEFENCE_ENDING_PHASE = 7;
const int DIGIMON_DEFENCE_GAMEOVER_PHASE = 8;
const int DIGIMON_DEFENCE_CLEAR_PHASE = 9;
extern int g_current_game_phase;